//Karina Alejandra Arriaza Ortiz 9959-24-14190
package Vista.Bancos;

import Controlador.Bancos.clsCatTipoTransaccion;
import Modelo.Bancos.CatTipoTransaccionDAO;
import java.io.File;
import java.sql.Connection;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class frmCatTipoTransaccion extends javax.swing.JInternalFrame {

    private final CatTipoTransaccionDAO dao = new CatTipoTransaccionDAO();

    public frmCatTipoTransaccion() {
        initComponents();
        setClosable(true);
        setMaximizable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cat. Tipo Transacción");
        cargarTabla();
        configurarSeleccionTabla();
        setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MS Gothic", 2, 14)); // NOI18N
        jLabel1.setText("Tipo Transacción");

        jLabel2.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel4.setText("Descripción:");

        jTextField1.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N

        txtid.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N

        jTextField3.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N

        btnAgregar.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnReporte.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnReporte.setText("Reportes");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnAyuda.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addGap(28, 28, 28)
                                .addComponent(btnEliminar)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnReporte))
                            .addComponent(btnAyuda)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar)
                            .addComponent(btnBuscar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnActualizar)
                                    .addComponent(btnEliminar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReporte)
                        .addGap(30, 30, 30)
                        .addComponent(btnAyuda)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
if (txtid.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione un tipo de transacción de la tabla o ingrese un ID.",
            "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "¿Está seguro de que desea eliminar este tipo de transacción?",
        "Confirmar eliminación", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    try {
        int id = Integer.parseInt(txtid.getText().trim());
        dao.delete(id);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Tipo de transacción eliminado correctamente.",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        frmBitacoraBancaria.registrarBitacora(
    "DELETE",
    "CatTipoTransaccion",
    Integer.parseInt(txtid.getText().trim()),
    "Nombre: " + jTextField1.getText().trim(),
    null,
    "Tipo de transacción eliminado"
);
        cargarTabla();
        limpiarCampos();
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "El ID debe ser un número válido.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al eliminar: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
if (txtid.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Ingrese un ID para buscar.",
            "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int id = Integer.parseInt(txtid.getText().trim());
        clsCatTipoTransaccion tt = dao.query(id);

        if (tt != null) {
            jTextField1.setText(tt.getTTnombretipo());
            txtid.setText(tt.getTTdescripcion());
            frmBitacoraBancaria.registrarBitacora(
    "SELECT",
    "CatTipoTransaccion",
    Integer.parseInt(txtid.getText().trim()),
    null,
    null,
    "Consulta de tipo de transacción por ID"
);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontró un tipo de transacción con ID: " + id,
                "Sin resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        }
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "El ID debe ser un número válido.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al buscar: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
Connection conn = null;
    try {
        conn = Modelo.Conexion.getConnection();
        
        // Ruta corregida — faltaba el separador entre getAbsolutePath() y src
        String ruta = new java.io.File("").getAbsolutePath() 
                    + "\\src\\main\\java\\Reportes\\Bancos\\CatTT.jrxml";
        
        System.out.println("Buscando reporte en: " + ruta); // Para verificar en consola
        
        java.io.File archivo = new java.io.File(ruta);
        if (!archivo.exists()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontró el archivo del reporte en:\n" + ruta,
                "Archivo no encontrado", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        java.util.Map<String, Object> parametros = new java.util.HashMap<>();
        
        net.sf.jasperreports.engine.JasperReport reporte =
            net.sf.jasperreports.engine.JasperCompileManager.compileReport(ruta);
        
        net.sf.jasperreports.engine.JasperPrint print =
            net.sf.jasperreports.engine.JasperFillManager.fillReport(reporte, parametros, conn);
        
        net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfFile(print,"reporte.pdf");
        net.sf.jasperreports.swing.JRViewer viewer = new net.sf.jasperreports.swing.JRViewer(print);
        
        javax.swing.JFrame frame = new javax.swing.JFrame("Reporte de Tipo Transacción");
        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        frame.add(viewer);
        frame.setVisible(true);
        
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al generar el reporte:\n" + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } finally {
        if (conn != null) {
            try { conn.close(); } catch (Exception ex) { ex.printStackTrace(); }
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        try {
            String ruta = "src\\main\\java\\Ayudas\\Bancos\\Ayuda Bancos.chm";

            File archivo = new File(ruta);

            if (archivo.exists()) {
                Runtime.getRuntime().exec("hh.exe \"" + ruta + "\"");
            } else {
                System.out.println("La ayuda no fue encontrada");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
if (!camposCompletos()) return;

    try {
        clsCatTipoTransaccion tt = getTipoTransaccionDeFormulario();
        dao.insert(tt);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Tipo de transacción registrado correctamente.",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        frmBitacoraBancaria.registrarBitacora(
    "INSERT",
    "CatTipoTransaccion",
    null,
    null,
    "Nombre: " + jTextField1.getText().trim() +
    " | Descripción: " + jTextField3.getText().trim(),
    "Tipo de transacción registrado"
);
        cargarTabla();
        limpiarCampos();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al agregar: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    if (txtid.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione un tipo de transacción de la tabla para actualizar.",
            "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!camposCompletos()) return;

    try {
        clsCatTipoTransaccion tt = getTipoTransaccionDeFormulario();
        tt.setTTid(Integer.parseInt(txtid.getText().trim()));
        dao.update(tt);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Tipo de transacción actualizado correctamente.",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        frmBitacoraBancaria.registrarBitacora(
    "UPDATE",
    "CatTipoTransaccion",
    Integer.parseInt(txtid.getText().trim()),
    null,
    "Nombre: " + jTextField1.getText().trim() +
    " | Descripción: " + jTextField3.getText().trim(),
    "Tipo de transacción actualizado"
);
        cargarTabla();
        limpiarCampos();
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "El ID debe ser un número válido.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al actualizar: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnActualizarActionPerformed
// ── Llena la tabla con todos los tipos de transacción ────────────────────
private void cargarTabla() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new String[]{"ID", "Nombre", "Descripción"}, 0
    ) {
        @Override
        public boolean isCellEditable(int r, int c) { return false; }
    };

    for (clsCatTipoTransaccion tt : dao.listar()) {
        modelo.addRow(new Object[]{
            tt.getTTid(),
            tt.getTTnombretipo(),
            tt.getTTdescripcion()
        });
    }
    jTable1.setModel(modelo);
}
// ── Clic en fila → llena campos automáticamente ──────────────
private void configurarSeleccionTabla() {
    jTable1.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
            int fila = jTable1.getSelectedRow();
            txtid.setText(jTable1.getValueAt(fila, 0).toString()); // ID
            jTextField1.setText(jTable1.getValueAt(fila, 1).toString()); // Nombre
            txtid.setText(jTable1.getValueAt(fila, 2).toString()); // Descripción
        }
    });
}

// ── Limpia todos los campos ──────────────────────────────────
private void limpiarCampos() {
    txtid.setText("");
    jTextField1.setText("");
    txtid.setText("");
    jTable1.clearSelection();
}

// ── Valida que los campos no estén vacíos ───────────────────
private boolean camposCompletos() {
    if (jTextField1.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Complete todos los campos: Nombre y Descripción.",
            "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return false;
    }
    return true;
}

// ── Crea el objeto clsCatTipoTransaccion desde los campos del formulario ─
private clsCatTipoTransaccion getTipoTransaccionDeFormulario() {
    clsCatTipoTransaccion tt = new clsCatTipoTransaccion(
        0,                             // ID lo genera MySQL con AUTO_INCREMENT
        jTextField1.getText().trim(),  // Nombre
        txtid.getText().trim()   // Descripción
    );
    return tt;
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCatTipoTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCatTipoTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCatTipoTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCatTipoTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCatTipoTransaccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
