/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 24-04-2026  1. Creacion frmMantenimientoTransporte, implementaciones basicas
                              //09-05-2026  2. Implementacion de funcionalidad de botones
                              //13-05-2023  4. Implementacion CRUD


package Vista.Logistica;

import Controlador.clsUsuarioConectado;
import Modelo.PermisosDAO;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import Controlador.Logistica.clsTransportistas;
import Modelo.Logistica.TransportistasDAO;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/**
 *
 * @author macoh
 */
public class frmMantenimientoTransporte extends javax.swing.JInternalFrame {
private DefaultTableModel modeloTransportes;

    public frmMantenimientoTransporte() {
        // 1. PRIMERO: NetBeans construye los botones, textos y tablas
        initComponents();
        
        // 2. SEGUNDO: Configuramos nuestra tabla manual
        modeloTransportes = new DefaultTableModel(new Object[]{"ID", "Nombre", "Tipo de Vehículo"}, 0);
        tablaTransporte.setModel(modeloTransportes);
        
        // 3. TERCERO: Cargamos datos existentes y permisos
        actualizarTabla();
        cargarPermisos();
        
        cargarDatosPrueba();

        // Configuración de la ventana
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        
    }
    public void cargarPermisos() {
        // Obtener el ID del usuario conectado
        int usuId = clsUsuarioConectado.getUsuId();
        PermisosDAO permisosDAO = new PermisosDAO();

        // 2000 es el código de la aplicación Mantenimiento Transportes
        int codigoAplicacion = 2000; 

        // Validamos únicamente el botón de Buscar
        btnBuscar.setEnabled(permisosDAO.puedeBuscar(usuId, codigoAplicacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTransporte = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        label15 = new javax.swing.JLabel();
        txtTipoVehiculo = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        label16 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtIdMovimiento2 = new javax.swing.JTextField();
        label17 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtIdMovimiento4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(782, 736));
        getContentPane().setLayout(null);

        tablaTransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Tipo de Vehiculo"
            }
        ));
        tablaTransporte.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaTransporteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tablaTransporte);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 290, 692, 300);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Transportistas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(264, 23, 160, 25);

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", "Tipo Vehiculo" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cboxTipoBusqueda);
        cboxTipoBusqueda.setBounds(10, 30, 124, 30);

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar);
        txtBuscar.setBounds(10, 70, 110, 30);

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(130, 70, 76, 31);

        label15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label15.setText("Tipo Vehiculo");
        getContentPane().add(label15);
        label15.setBounds(20, 220, 84, 16);

        txtTipoVehiculo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTipoVehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtTipoVehiculo);
        txtTipoVehiculo.setBounds(120, 220, 170, 17);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(430, 140, 80, 30);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(430, 170, 86, 27);

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAyuda);
        btnAyuda.setBounds(600, 220, 76, 27);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(350, 210, 77, 27);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(340, 140, 80, 27);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(340, 170, 85, 27);

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes);
        btnReportes.setBounds(520, 220, 80, 27);

        label16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label16.setText("ID");
        getContentPane().add(label16);
        label16.setBounds(20, 140, 12, 16);

        txtId.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtId);
        txtId.setBounds(120, 140, 170, 17);

        txtIdMovimiento2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdMovimiento2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtIdMovimiento2);
        txtIdMovimiento2.setBounds(120, 140, 140, 17);

        label17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label17.setText("Nombre");
        getContentPane().add(label17);
        label17.setBounds(20, 180, 48, 16);

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtNombre);
        txtNombre.setBounds(120, 180, 170, 17);

        txtIdMovimiento4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdMovimiento4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtIdMovimiento4);
        txtIdMovimiento4.setBounds(120, 180, 140, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaTransporteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaTransporteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaTransporteAncestorAdded

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed

        txtBuscar.setText("");
        txtBuscar.requestFocus();
        String seleccion = cboxTipoBusqueda.getSelectedItem().toString();
        switch (seleccion) {
            case "ID Movimiento":
            buscarPorID();
            break;
            case "Tipo de Movimiento":
            buscarPorNombre();
            break;
            case "Producto":
            buscarPorTipoVehiculo();
            break;
   
        }
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String filtro = txtBuscar.getText().trim().toLowerCase();
        String criterio = cboxTipoBusqueda.getSelectedItem().toString();
        boolean encontrado = false;

        if (filtro.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor para buscar.");
            return;
        }
        int columna = 0;
        if (criterio.equals("ID Movimiento")) columna = 0;
        else if (criterio.equals("Tipo de Movimiento")) columna = 1;
        else if (criterio.equals("Producto")) columna = 2;
        else if (criterio.equals("Fecha")) columna = 3;

        for (int i = 0; i < tablaTransporte.getRowCount(); i++) {
            String valorCelda = tablaTransporte.getValueAt(i, columna).toString().toLowerCase();

            if (valorCelda.contains(filtro)) {
                tablaTransporte.setRowSelectionInterval(i, i);
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró coincidencia para: " + filtro);
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String filtro = txtBuscar.getText().trim();
        String criterio = cboxTipoBusqueda.getSelectedItem().toString();

        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) tablaTransporte.getModel());
        tablaTransporte.setRowSorter(sorter);

        if (filtro.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            int indiceColumna = 0;
            switch (criterio) {
                case "ID":
                indiceColumna = 0;
                break;
                case "Nombre":
                indiceColumna = 1;
                break;
                case "Tipo Vehiculo":
                indiceColumna = 2;
                break;
                default:
                indiceColumna = 0;
                break;
            }

            try {

                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, indiceColumna));
                if (tablaTransporte.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
                }
            } catch (Exception e) {
                System.err.println("Error en el filtro: " + e.getMessage());
            }
        }
        //Registro de la accion en bitacora
        //     BitacoraDAO bitacoraDAO = new BitacoraDAO();
        //    bitacoraDAO.insert(idUsuario, Aplcodigo, "CONSULTA");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtTipoVehiculo.setText("");
        txtId.setText("");
        txtNombre.setText("");
        tablaTransporte.clearSelection();
        cboxTipoBusqueda.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (tablaTransporte.getRowSorter() != null) {
            tablaTransporte.setRowSorter(null);
        }
        txtBuscar.setText("");
        cboxTipoBusqueda.setSelectedIndex(0);

        txtTipoVehiculo.setText("");
        txtNombre.setText("");
        txtId.setText("");

        tablaTransporte.clearSelection();

        JOptionPane.showMessageDialog(this, "Formulario restablecido correctamente.");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();

        ventanaAyuda.setVisible(true);
        ventanaAyuda.setLocationRelativeTo(null);
        //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyFinalP32K26b\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int filaSeleccionada = tablaTransporte.getSelectedRow();

        if (filaSeleccionada != -1) {

            int filaModelo = tablaTransporte.convertRowIndexToModel(filaSeleccionada);

            int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este movimiento?",
                "Confirmación de eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {

                modeloTransportes.removeRow(filaModelo);

                btnLimpiarActionPerformed(null);

                JOptionPane.showMessageDialog(this, "Registro eliminado correctamente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila de la tabla para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
      String id = txtId.getText();
    String nombre = txtNombre.getText();
    String vehiculo = txtTipoVehiculo.getText();
    
    if (id.isEmpty() || nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Complete los campos básicos (ID y Nombre)");
        return;
    }

    // Usamos llaves {} para inicializar el arreglo correctamente
    Object[] nuevaFila = {id, nombre, vehiculo};
    modeloTransportes.addRow(nuevaFila);
    
    JOptionPane.showMessageDialog(this, "Registro agregado exitosamente.");
    btnLimpiarActionPerformed(null);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
int filaVisual = tablaTransporte.getSelectedRow();

    if (filaVisual != -1) {
        int filaModelo = tablaTransporte.convertRowIndexToModel(filaVisual);

        if (!txtId.getText().trim().isEmpty()) {
            modeloTransportes.setValueAt(txtId.getText(), filaModelo, 0);
        }
        if (!txtNombre.getText().trim().isEmpty()) {
            modeloTransportes.setValueAt(txtNombre.getText(), filaModelo, 1);
        }
        if (!txtTipoVehiculo.getText().trim().isEmpty()) {
            modeloTransportes.setValueAt(txtTipoVehiculo.getText(), filaModelo, 2);
        }

        JOptionPane.showMessageDialog(this, "Cambios aplicados únicamente a los campos editados.");
        btnLimpiarActionPerformed(null); 
        
    } else {
        JOptionPane.showMessageDialog(this, "Primero selecciona un registro de la tabla.");
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Vista.Logistica.frmReportes ventana = new Vista.Logistica.frmReportes();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoTransporte().setVisible(true));
    }
    
    
    private void buscarPorID() {
        System.out.println("Buscando por ID...");
      
    }

    private void buscarPorNombre() {
        System.out.println("Buscando por Nombre...");
    }

    private void buscarPorTipoVehiculo() {
        System.out.println("Buscando por Vehiculo...");
    }

  
    
   public void actualizarTabla() {
    Modelo.Logistica.TransportistasDAO transporteDAO = new Modelo.Logistica.TransportistasDAO();
    // Usamos el nombre exacto de tu DAO: listar()
    List<Controlador.Logistica.clsTransportistas> lista = transporteDAO.listar();

    modeloTransportes.setRowCount(0); 

    for (Controlador.Logistica.clsTransportistas t : lista) {
        modeloTransportes.addRow(new Object[]{
            t.getTranid(),            // Coincide con tu controlador
            "Empleado " + t.getEmpcodigo(), 
            t.getTrantipovehiculo()   // Coincide con tu controlador
        });
    }
}
   
   private void cargarDatosPrueba() {
    // Simulamos que el sistema "jaló" estos 3 choferes de la base de datos
    modeloTransportes.addRow(new Object[]{"1", "Marco Hernandez", "Camión de Carga"});
    modeloTransportes.addRow(new Object[]{"2", "Juan Pérez", "Panel Reparto"});
    modeloTransportes.addRow(new Object[]{"3", "Luis Gómez", "Motocicleta"});
}
   
   private void tablaTransporteMouseClicked(java.awt.event.MouseEvent evt) {                                             
    int filaVisual = tablaTransporte.getSelectedRow();
    
    if (filaVisual != -1) {
        // Convertimos el índice por si la tabla está filtrada
        int filaModelo = tablaTransporte.convertRowIndexToModel(filaVisual);
        
        // Extraemos datos del modelo y los subimos a los campos
        txtId.setText(modeloTransportes.getValueAt(filaModelo, 0).toString());
        txtNombre.setText(modeloTransportes.getValueAt(filaModelo, 1).toString());
        txtTipoVehiculo.setText(modeloTransportes.getValueAt(filaModelo, 2).toString());
    }
}
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JTable tablaTransporte;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdMovimiento2;
    private javax.swing.JTextField txtIdMovimiento4;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipoVehiculo;
    // End of variables declaration//GEN-END:variables
}
